language: node_js
node_js:
  - 7
env:
  - CXX=g++-4.8
  - NODE_ENV=test
addons:
before_install:
    - npm install node-pre-gyp typescript -g
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
    - npm install
script:
    - npm build
    - npm run test
    - npm run coverage