language: node_js
node_js:
  - 6
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.12.0
before_install:
  - npm install -g typescript node-gyp nyc
env:
  - CXX=g++-4.8
  - NODE_ENV=test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
    - npm install
script:
    - npm build
    - npm run test:integration